services:
  app:
    image: ghcr.io/vas3k/taxhacker:latest
    ports:
      - "7331:7331"
    environment:
      - NODE_ENV=production
      - SELF_HOSTED_MODE=true
      - UPLOAD_PATH=/app/data/uploads
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/redecruzada
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    depends_on:
      - postgres
    logging:
      driver: "local"
      options:
        max-size: "100M"
        max-file: "3"

  postgres:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=redecruzada
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    logging:
      driver: "local"
      options:
        max-size: "100M"
        max-file: "3"

  db-backup:
    image: prodrigestivill/postgres-backup-local
    restart: unless-stopped
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=redecruzada
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - SCHEDULE=@daily
      - BACKUP_KEEP_DAYS=14
      - BACKUP_DIR=/backups
    volumes:
      - ./pgbackups:/backups
    depends_on:
      - postgres
